baseURL = 'https://pemsite.netlify.app/'
languageCode = 'en-us'
title = 'Pemsite'
theme = 'hClarity'

# title = "Clarity"  # Edit directly from config/_default/languages.toml # alternatively, uncomment this and remove `title` entry from the aforemention file.
copyright = "Copyright Â© 2025, pmX; all rights reserved."
# canonifyurls = true

disqusShortname = ""

DefaultContentLanguage = "en"
# [languages]
# config/_default/languages.toml

# [menus]
# config/_default/menus/menu.xx.toml

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 10
